version: "3.8"

services:
  platform-configuration-svc:
    image: mojaloop/platform-configuration-bc-configuration-svc:alpha-latest
    volumes:
      - platform-configuration-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
    healthcheck:
      test: nc -z localhost 3100 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3100:3100
    restart: unless-stopped

  authentication-svc:
    image: mojaloop/security-bc-authentication-svc:alpha-latest
    # depends_on:
    #   platform-configuration-svc:
    #     condition: service_healthy
    volumes:
      - authentication-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:9092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - AUTH_N_TOKEN_LIFE_SECS=604800
      - AUTH_N_DEFAULT_AUDIENCE=mojaloop.vnext.dev.default_audience
      - AUTH_N_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
    ports:
      - 3201:3201
    restart: unless-stopped

  authorization-svc:
    image: mojaloop/security-bc-authorization-svc:alpha-latest
    # depends_on:
    #   platform-configuration-svc:
    #     condition: service_healthy
    volumes:
      - authorization-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
    ports:
      - 3202:3202
    restart: unless-stopped



  auditing-svc:
    image: mojaloop/auditing-bc-auditing-svc:alpha-latest
    volumes:
      - auditing-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - ELASTICSEARCH_URL=https://es01:9200
      - ELASTICSEARCH_AUDITS_INDEX=ml-auditing
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elasticSearchPas42
    restart: unless-stopped

  logging-svc:
    image: mojaloop/logging-bc-logging-svc:alpha-latest
    volumes:
      - logging-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - ELASTICSEARCH_URL=https://es01:9200
      - ELASTICSEARCH_AUDITS_INDEX=ml-auditing
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elasticSearchPas42
    restart: unless-stopped

volumes:
  authentication-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/authentication-svc
  authorization-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/authorization-svc
  platform-configuration-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/platform-configuration-svc
  auditing-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/auditing-svc
  logging-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/logging-svc
