apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: ttk-ui-1
    mojaloop.layer: apps
  name: ttk-ui-1
spec:
  ports:
    - name: "6060"
      port: 6060
      targetPort: 6060
  selector:
    mojaloop.service: ttk-ui-1
status:
  loadBalancer: {}
