apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: account-lookup-http-oracle-svc
  name: account-lookup-http-oracle-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-lookup-http-oracle-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-apps.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: account-lookup-http-oracle-svc
    spec:
      containers:
        - env:
            - name: KAFKA_AUDITS_TOPIC
              value: audits
            - name: KAFKA_LOGS_TOPIC
              value: logs
            - name: KAFKA_URL
              value: kafka:19092
          image: mojaloop/account-lookup-bc-http-oracle-svc:0.1.1
          livenessProbe:
            exec:
              command:
                - nc -z localhost 3031 || exit -1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: account-lookup-http-oracle-svc
          ports:
            - containerPort: 3031
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: account-lookup-http-oracle-svc-data
      restartPolicy: Always
      volumes:
        - name: account-lookup-http-oracle-svc-data
          persistentVolumeClaim:
            claimName: account-lookup-http-oracle-svc-data
status: {}
