version: "3.8"

services:
  fspiop-api-svc:
    image: mojaloop/interop-apis-bc-fspiop-api-svc:alpha-latest
    # depends_on:
    #   settlements-api-svc:
    #     condition: service_healthy
    #   participants-svc:
    #     condition: service_healthy
    #   account-lookup-svc:
    #     condition: service_healthy
    #   quoting-svc:
    #     condition: service_healthy
    #   transfers-api-svc:
    #     condition: service_healthy
    volumes:
      - fspiop-api-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
    ports:
      - 4000:4000

  accounts_and_balances_builtin-ledger-grpc-svc:
    image: mojaloop/accounts-and-balances-bc-builtin-ledger-grpc-svc:alpha-latest
    volumes:
      - aandb_builtin-ledger-grpc-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - TIGERBEETLE_CLUSTER_ID=0
      - TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES=tigerbeetle:3000
    healthcheck:
      test: nc -z localhost 3350 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3350:3350
    restart: unless-stopped

  accounts_and_balances_coa-grpc-svc:
    image: mojaloop/accounts-and-balances-bc-coa-grpc-svc:alpha-latest
    # depends_on:
    #   accounts_and_balances_builtin-ledger-grpc-svc:
    #     condition: service_healthy
    volumes:
      - aandb_coa-grpc-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - TIGERBEETLE_CLUSTER_ID=0
      - TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES=tigerbeetle:3000
      - BUILTIN_LEDGER_SVC_URL=accounts_and_balances_builtin-ledger-grpc-svc:3350
    healthcheck:
      test: nc -z localhost 3300 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3300:3300
    restart: unless-stopped

# participants

  participants-svc:
    image: mojaloop/participants-bc-participants-svc:0.1.4
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
    volumes:
      - participants-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - TIGERBEETLE_CLUSTER_ID=0
      - TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES=tigerbeetle:3000
      - ACCOUNTS_BALANCES_COA_SVC_URL=accounts_and_balances_coa-grpc-svc:3300
    healthcheck:
      test: nc -z localhost 3010 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3010:3010
    restart: unless-stopped

#account lookup

  account-lookup-http-oracle-svc:
    image: mojaloop/account-lookup-bc-http-oracle-svc:0.1.1
    # depends_on:
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - account-lookup-http-oracle-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
    healthcheck:
      test: nc -z localhost 3031 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3031:3031
    restart: unless-stopped

  account-lookup-svc:
    image: mojaloop/account-lookup-bc-account-lookup-svc:alpha-latest
    # depends_on:
    #   account-lookup-http-oracle-svc:
    #     condition: service_healthy
    volumes:
      - account-lookup-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
    healthcheck:
      test: nc -z localhost 3030 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3030:3030
    restart: unless-stopped

# quoting

  quoting-svc:
    image: mojaloop/quoting-bc-quoting-svc:alpha-latest
    # depends_on:
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - quoting-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
    healthcheck:
      test: nc -z localhost 3033 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3033:3033
    restart: unless-stopped

# transfers

  transfers-api-svc:
    image: mojaloop/transfers-bc-transfers-api-svc:alpha-latest
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
      # participants-svc:
      #   condition: service_healthy
    volumes:
      - transfers-api-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
    healthcheck:
      test: nc -z localhost 3500 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3500:3500
    restart: unless-stopped

  transfers-event-handler-svc:
    image: mojaloop/transfers-bc-event-handler-svc:alpha-latest
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - transfers-event-handler-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
    restart: unless-stopped

  transfers-command-handler-svc:
    image: mojaloop/transfers-bc-command-handler-svc:alpha-latest
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - transfers-command-handler-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
      - ACCOUNTS_BALANCES_COA_SVC_URL=accounts_and_balances_coa-grpc-svc:3300
    restart: unless-stopped

# settlements

  settlements-api-svc:
    image: mojaloop/settlements-bc-settlements-api-svc:0.1.3
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - settlements-api-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
      - ACCOUNTS_BALANCES_COA_SVC_URL=accounts_and_balances_coa-grpc-svc:3300
    healthcheck:
      test: nc -z localhost 3600 || exit -1
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 3600:3600
    restart: unless-stopped

  settlements-event-handler-svc:
    image: mojaloop/settlements-bc-event-handler-svc:0.1.2
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - settlements-event-handler-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
    restart: unless-stopped

  settlements-command-handler-svc:
    image: mojaloop/settlements-bc-command-handler-svc:0.1.3
    # depends_on:
    #   accounts_and_balances_coa-grpc-svc:
    #     condition: service_healthy
    #   participants-svc:
    #     condition: service_healthy
    volumes:
      - settlements-command-handler-svc_data:/app/data
    environment:
      - KAFKA_URL=kafka:19092
      - KAFKA_LOGS_TOPIC=logs
      - KAFKA_AUDITS_TOPIC=audits
      - MONGO_URL=mongodb://root:mongoDbPas42@mongo:27017/
      - PLATFORM_CONFIG_BASE_SVC_URL=http://platform-configuration-svc:3100
      - AUTH_Z_SVC_BASEURL=http://authorization-svc:3202
      - AUTH_N_SVC_BASEURL=http://authentication-svc:3201
      - AUTH_N_TOKEN_ISSUER_NAME=mojaloop.vnext.dev.default_issuer
      - AUTH_N_TOKEN_AUDIENCE=mojaloop.vnext.dev.default_audience
      - PARTICIPANTS_SVC_URL=http://participants-svc:3010
      - ACCOUNTS_BALANCES_COA_SVC_URL=accounts_and_balances_coa-grpc-svc:3300
    restart: unless-stopped


  admin-ui:
    image: mojaloop/vnext-admin-ui-svc:0.1.8
    # depends_on:
    #   transfers-api-svc:
    #     condition: service_healthy
    #   settlements-api-svc:
    #     condition: service_healthy
    ports:
      - 4200:4200


  # blue bank TTK
  ttk_1:
    image: mojaloop/ml-testing-toolkit:v15.0.0
    volumes:
      - ttk1_data:/opt/app
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    ports:
      - "4040:4040"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"
  ttk-ui_1:
    image: mojaloop/ml-testing-toolkit-ui:v15.0.0
    ports:
      - "6060:6060"
    volumes:
      - ttk1_ui_data:/usr/share/nginx/html
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

  # green bank TTK
  ttk_2:
    image: mojaloop/ml-testing-toolkit:v15.0.0
    volumes:
      - ttk2_data:/opt/app
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    ports:
      - "4041:4040"
      - "5051:5050"
    command:
      - sh
      - -c
      - "npm start"
  ttk-ui_2:
    image: mojaloop/ml-testing-toolkit-ui:v15.0.0
    ports:
      - "6061:6060"
    volumes:
      - ttk2_ui_data:/usr/share/nginx/html
    environment:
      - API_BASE_URL=http://localhost:5051
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

volumes:
  participants-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/participants-svc
  account-lookup-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/account-lookup-svc
  account-lookup-http-oracle-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/account-lookup-http-oracle-svc
  quoting-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/quoting-svc
  fspiop-api-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/fspiop-api-svc
  aandb_builtin-ledger-grpc-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/aandb_builtin-ledger-grpc-svc
  aandb_coa-grpc-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/aandb_coa-grpc-svc
  transfers-api-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/transfers-api-svc
  transfers-event-handler-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/transfers-event-handler-svc
  transfers-command-handler-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/transfers-command-handler-svc
  settlements-api-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/settlements-api-svc
  settlements-event-handler-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/settlements-event-handler-svc
  settlements-command-handler-svc_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/settlements-command-handler-svc
  ttk1_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/ttk1_data
  ttk2_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/ttk2_data
  ttk1_ui_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/ttk1_ui_data
  ttk2_ui_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./exec/data/ttk2_ui_data
