apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: settlements-api-svc
  name: settlements-api-svc
spec:
  ports:
    - name: "3600"
      port: 3600
      targetPort: 3600
  selector:
    io.kompose.service: settlements-api-svc
status:
  loadBalancer: {}
