apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ttk-ui-1
  name: ttk-ui-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ttk-ui-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-apps.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ttk-ui-1
    spec:
      containers:
        - args:
            - sh
            - /usr/share/nginx/start.sh
          env:
            - name: API_BASE_URL
              value: http://localhost:5050
            - name: AUTH_ENABLED
              value: "FALSE"
          image: mojaloop/ml-testing-toolkit-ui:v15.0.0
          name: ttk-ui_1
          ports:
            - containerPort: 6060
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: ttk1-ui-data
      restartPolicy: Always
      volumes:
        - name: ttk1-ui-data
          persistentVolumeClaim:
            claimName: ttk1-ui-data
status: {}
