apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ttk-2
  name: ttk-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ttk-2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-apps.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ttk-2
    spec:
      containers:
        - args:
            - sh
            - -c
            - npm start
          image: mojaloop/ml-testing-toolkit:v15.0.0
          name: ttk_2
          ports:
            - containerPort: 4040
            - containerPort: 5050
          resources: {}
          volumeMounts:
            - mountPath: /opt/app
              name: ttk2-data
      restartPolicy: Always
      volumes:
        - name: ttk2-data
          persistentVolumeClaim:
            claimName: ttk2-data
status: {}
