apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: logging-svc
  name: logging-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: logging-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        mojaloop.service: logging-svc
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_AUDITS_INDEX
              value: ml-auditing
            - name: ELASTICSEARCH_PASSWORD
              value: elasticSearchPas42
            - name: ELASTICSEARCH_URL
              value: https://es01:9200
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: KAFKA_LOGS_TOPIC
              value: logs
            - name: KAFKA_URL
              value: kafka:9092
          image: mojaloop/logging-bc-logging-svc:alpha-latest
          name: logging-svc
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: logging-svc-data
      restartPolicy: Always
      volumes:
        - name: logging-svc-data
          persistentVolumeClaim:
            claimName: logging-svc-data
status: {}
