apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    mojaloop.service: authentication-svc
    mojaloop.layer: crosscut
  name: authentication-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: authentication-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        mojaloop.service: authentication-svc
        mojaloop.layer: crosscut
    spec:
      containers:
      - env:
        - name: AUTH_N_DEFAULT_AUDIENCE
          value: mojaloop.vnext.dev.default_audience
        - name: AUTH_N_ISSUER_NAME
          value: mojaloop.vnext.dev.default_issuer
        - name: AUTH_N_TOKEN_LIFE_SECS
          value: "604800"
        - name: KAFKA_AUDITS_TOPIC
          value: audits
        - name: KAFKA_LOGS_TOPIC
          value: logs
        - name: KAFKA_URL
          value: kafka:9092
        - name: MONGO_URL
          value: mongodb://root:mongoDbPas42@mongodb:27017/
        image: mojaloop/security-bc-authentication-svc:snapshot
        name: authentication-svc
        ports:
        - containerPort: 3201
        resources: {}
      restartPolicy: Always
