apiVersion: vnext.mojaloop.io/v1
kind: MojaloopVNextInstall
metadata:
  name: mojaloop-vnext-install-sample
  namespace: mojaloop-vnext
spec:
  services:
    - svcName: logging-svc
      image: mojaloop/logging-bc-logging-svc:0.1.9
      bcName: security-bc
      layer: cross-cutting
      size: 1
