apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mojaloop-vnext-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mojaloop-vnext-install-editor-role
subjects:
  - kind: ServiceAccount
    name: vnext-operator-sa
    namespace: mojaloop-vnext-operator
