apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mojaloop-vnext-operator
  annotations:
    deployment.kubernetes.io/revision: '4'
  labels:
    app: vnext-operator
    app.kubernetes.io/component: vnext-operator
    app.kubernetes.io/instance: vnext-operator
  name: vnext-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: vnext-operator
  template:
    metadata:
      labels:
        deployment: vnext-operator
    spec:
      containers:
        - env:
            - name: DEV_MODE
              value: 'true'
          image: mojaloop/mojaloop-vnext-k8s-operator-svc:0.0.3
          imagePullPolicy: IfNotPresent
          name: vnext-operator
      serviceAccountName: vnext-operator-sa
