apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: authorization-svc
    mojaloop.layer: crosscut
  name: authorization-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: authorization-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        mojaloop.service: authorization-svc
        mojaloop.layer: crosscut
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: vnext-configs
          image: mojaloop/security-bc-authorization-svc:0.6.2
          name: authorization-svc
          ports:
          - containerPort: 3202
          resources: {}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - nc -z localhost 3202
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      restartPolicy: Always
status: {}
