apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: scheduling-command-handler-svc
    mojaloop.layer: crosscut
  name: scheduling-command-handler-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: scheduling-command-handler-svc
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
          mojaloop.service: scheduling-command-handler-svc
          mojaloop.layer: crosscut
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: vnext-configs
          image: mojaloop/scheduling-bc-command-handler-svc:0.5.3
          name: scheduling-command-handler-svc
          resources: {}
      restartPolicy: Always
