apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: account-lookup-http-oracle-svc
  name: account-lookup-http-oracle-svc
spec:
  ports:
    - name: "3031"
      port: 3031
      targetPort: 3031
  selector:
    io.kompose.service: account-lookup-http-oracle-svc
status:
  loadBalancer: {}
