apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: accounts-and-balances-builtin-ledger-grpc-svc
  name: accounts-and-balances-builtin-ledger-grpc-svc
spec:
  ports:
    - name: "3350"
      port: 3350
      targetPort: 3350
  selector:
    io.kompose.service: accounts-and-balances-builtin-ledger-grpc-svc
status:
  loadBalancer: {}
