apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: quoting-svc
  name: quoting-svc
spec:
  ports:
    - name: "3033"
      port: 3033
      targetPort: 3033
  selector:
    io.kompose.service: quoting-svc
status:
  loadBalancer: {}
