apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ttk-1
  name: ttk-1
spec:
  ports:
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "5050"
      port: 5050
      targetPort: 5050
  selector:
    io.kompose.service: ttk-1
status:
  loadBalancer: {}
