apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    mojaloop.service: aandb-builtin-ledger-grpc-svc-data
    mojaloop.layer: apps
  name: aandb-builtin-ledger-grpc-svc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
