apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: account-lookup-http-oracle-svc
    mojaloop.layer: apps
  name: account-lookup-http-oracle-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: account-lookup-http-oracle-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: account-lookup-http-oracle-svc
        mojaloop.layer: apps
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: vnext-configs
        image: mojaloop/account-lookup-bc-http-oracle-svc:0.5.4
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - nc -z localhost 3031
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        name: account-lookup-http-oracle-svc
        ports:
        - containerPort: 3031
        resources: {}
      restartPolicy: Always

