apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: accounts-and-balances-coa-grpc-svc
    mojaloop.layer: apps
  name: accounts-and-balances-coa-grpc-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: accounts-and-balances-coa-grpc-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: accounts-and-balances-coa-grpc-svc
        mojaloop.layer: apps
    spec:
      containers:
      - env:
        - name: BUILTIN_LEDGER_SVC_URL
          value: accounts-and-balances-builtin-ledger-grpc-svc:3350
        - name: UV_THREADPOOL_SIZE
          value: "32"
        - name: USE_TIGERBEETLE
          value: "false"
        - name: TIGERBEETLE_CLUSTER_ID
          value: "0"
        - name: TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES
          value: tigerbeetle-svc:13000
        envFrom:
          - configMapRef:
              name: vnext-configs
        image: mojaloop/accounts-and-balances-bc-coa-grpc-svc:0.6.4
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - nc -z localhost 3301
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        name: accounts-and-balances-coa-grpc-svc
        ports:
        - containerPort: 3300
        resources: {}
      restartPolicy: Always
