apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: accounts-and-balances-builtin-ledger-grpc-svc
    mojaloop.layer: apps
  name: accounts-and-balances-builtin-ledger-grpc-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: accounts-and-balances-builtin-ledger-grpc-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: accounts-and-balances-builtin-ledger-grpc-svc
        mojaloop.layer: apps
    spec:
      containers:
      - env:
        - name: UV_THREADPOOL_SIZE
          value: "32"
        - name: LOG_LEVEL
          value: debug
        envFrom:
          - configMapRef:
              name: vnext-configs
        image: mojaloop/accounts-and-balances-bc-builtin-ledger-grpc-svc:0.6.4
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - nc -z localhost 3351
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        name: accounts-and-balances-builtin-ledger-grpc-svc
        ports:
        - containerPort: 3350
        resources: {}
      restartPolicy: Always
