apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: participants-svc
    mojaloop.layer: apps
  name: participants-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: participants-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: participants-svc
        mojaloop.layer: apps
    spec:
      containers:
      - env:
        - name: ACCOUNTS_BALANCES_COA_SVC_URL
          value: accounts-and-balances-coa-grpc-svc:3300
        envFrom:
          - configMapRef:
              name: vnext-configs
        image: mojaloop/participants-bc-participants-svc:0.6.4
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - nc -z localhost 3010
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        name: participants-svc
        ports:
        - containerPort: 3010
        resources: {}
      restartPolicy: Always
