apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: settlements-api-svc
    mojaloop.layer: apps
  name: settlements-api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: settlements-api-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: settlements-api-svc
        mojaloop.layer: apps
    spec:
      containers:
      - env:
        - name: ACCOUNTS_BALANCES_COA_SVC_URL
          value: accounts-and-balances-coa-grpc-svc:3300
        - name: AUTH_N_SVC_BASEURL
          value: http://authentication-svc:3201
        envFrom:
        - configMapRef:
            name: vnext-configs
        image: mojaloop/settlements-bc-settlements-api-svc:0.6.1
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - nc -z localhost 3600
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        name: settlements-api-svc
        ports:
        - containerPort: 3600
        resources: {}
      restartPolicy: Always
