apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: transfers-event-handler-svc
    mojaloop.layer: apps
  name: transfers-event-handler-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: transfers-event-handler-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: transfers-event-handler-svc
        mojaloop.layer: apps
    spec:
      containers:
      - env:
        - name: CONSUMER_BATCH_SIZE
          value: "150"
        - name: CONSUMER_BATCH_TIMEOUT_MS
          value: "5"
        - name: UV_THREADPOOL_SIZE
          value: "64"
        - name: LOG_LEVEL
          value: debug
        envFrom:
          - configMapRef:
              name: vnext-configs
        image: mojaloop/transfers-bc-event-handler-svc:0.6.4
        name: transfers-event-handler-svc
        resources: {}
      restartPolicy: Always
