{
 "title": "Account Lookup",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheusSource", "label": "PrometheusDataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Simulator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(Simulator_lookups_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Max total time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (max((rate(Simulator_lookups_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_lookups_count{leg=\"total\"}[$__rate_interval]))>=0) [$__range:$__rate_interval])",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Avg time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ((rate(Simulator_lookups_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_lookups_count{leg=\"total\"}[$__rate_interval])>=0)\n)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Req(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(increase(Simulator_lookups_count{leg=\"total\"}[$__range])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(increase(Simulator_lookups_count{leg=\"total\", success!=\"true\"}[$__range])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(increase(Simulator_lookups_count{leg=\"total\"}[5m]) >= 6666600)\n",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Durations Measured at the Simulators",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(leg) ( rate(Simulator_lookups_sum[$__rate_interval]) / rate(Simulator_lookups_count[$__rate_interval]) >=0 )",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": " sum(rate(Simulator_lookups_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "Requests/Sec"
    }
   ]
  },
  { "title": "FSPIOP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Reqs / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{route=~\"/parties/.*\",status_code=~\"20[0-9]\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Errors / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(AccountLookupEventHandler_count{success=\"false\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "GET Parties / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{route=\"/parties/:type/:id\", method=\"GET\"}[$__interval])>0)",
     "legendFormat": "GET Parties / Sec"
    }
   ]
  },
  {
   "title": "PUT Parties / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{route=\"/parties/:type/:id\", method=\"PUT\"}[$__interval])>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "handlePartyInfoRequestedEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(AccountLookupEventHandler_count{callName=\"handlePartyInfoRequestedEvt\"}[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "handlePartyQueryResponseEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(AccountLookupEventHandler_count{callName=\"handlePartyQueryResponseEvt\"}[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance_id) (nodejs_version_info{app=\"fspiop-api-svc\"}))",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Evt Handler Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance_id) (nodejs_version_info{app=\"fspiop-event-handler-svc\"}))",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "FSPIOP - API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method,route) (rate(http_request_duration_seconds_sum{app=\"fspiop-api-svc\",route=~\"/parties/.*\"}[$__interval]) / rate(http_request_duration_seconds_count{app=\"fspiop-api-svc\",route=~\"/parties/.*\"}[$__interval]) >= 0)",
     "legendFormat": "{{method}} {{route}}"
    },
    {
     "expr": "avg by(callName) (rate(PartyRoutes_sum[$__interval]) / rate(PartyRoutes_count[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "FSPIOP - AccountLookupEventHandler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(AccountLookupEventHandler_sum[$__interval]) / rate(AccountLookupEventHandler_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AccountLookup Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Ops / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(AccountLookupEventHandler_count{success=\"true\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Errors / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(AccountLookupAggregate_count{success=\"false\"}[$__interval])  >= 0",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "handlePartyQueryReceivedEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(AccountLookupAggregate_count{callName=\"handlePartyQueryReceivedEvt\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "handlePartyInfoAvailableEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(AccountLookupAggregate_count{callName=\"handlePartyInfoAvailableEvt\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance_id) (nodejs_version_info{app=\"account-lookup-svc\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AccountLookup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(AccountLookupAggregate_sum[$__interval]) / rate(AccountLookupAggregate_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}