{
 "title": "Account Lookup",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheusSource", "label": "PrometheusDataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "FSPIOP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ops / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(AccountLookupEventHandler_count{success=\"true\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Ops / sec (error)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(AccountLookupEventHandler_count{success=\"false\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "API Reqs / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"20[0-9]\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "API Reqs / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"20[0-9]\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "handlePartyQueryResponseEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(AccountLookupEventHandler_count{callName=\"handlePartyQueryResponseEvt\"}[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FSPIOP - AccountLookupEventHandler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(AccountLookupEventHandler_sum[$__interval]) / rate(AccountLookupEventHandler_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /parties/MSISDN/? / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(http_request_duration_seconds_count{path=\"/parties/MSISDN/#val\"}[$__interval])>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FSPIOP - API Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(path) (rate(http_request_duration_seconds_sum{app=\"fspiop-api-svc\"}[$__interval]) / rate(http_request_duration_seconds_count{app=\"fspiop-api-svc\"}[$__interval]) >= 0)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "AccountLookup SVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Ops / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(AccountLookupAggregate_count{callName=\"handleAccountLookUpEvent\", success=\"true\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Ops / sec (error)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(AccountLookupAggregate_count{callName=\"handleAccountLookUpEvent\", success=\"false\"}[$__interval])  >= 0",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "AccountLookup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(AccountLookupAggregate_sum[30s]) / rate(AccountLookupAggregate_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}