{
 "title": "Quotes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheusSource", "label": "PrometheusDataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Simulator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(Simulator_quotes_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Max total time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (max((rate(Simulator_quotes_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_quotes_count{leg=\"total\"}[$__rate_interval]))>=0) [$__range:$__rate_interval])",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Avg time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ((rate(Simulator_quotes_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_quotes_count{leg=\"total\"}[$__rate_interval])>=0)\n)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Req(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(increase(Simulator_quotes_count{leg=\"total\"}[$__range])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(increase(Simulator_quotes_count{leg=\"total\", success!=\"true\"}[$__range])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Durations Measured at the Simulators",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(leg) (rate(Simulator_quotes_sum[$__rate_interval]) / rate(Simulator_quotes_count[$__rate_interval]) >=0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(Simulator_quotes_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "Requests/Sec"
    }
   ]
  },
  { "title": "FSPIOP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ops / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(QuotingEventHandler_count{success=\"true\",app=\"fspiop-event-handler-svc\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Ops / sec (error)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(QuotingEventHandler_count{success=\"false\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "API Reqs / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{path!=\"/metrics\",path=\"/parties/MSISDN/#val\", status_code=~\"20[0-9]\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "API Reqs / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{path!=\"/metrics\",status_code=~\"20[0-9]\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "handleQuoteRequestAcceptedEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(QuotingEventHandler_count{callName=\"handleQuoteRequestAcceptedEvt\"}[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "handleQuoteResponseAcceptedEvt / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(QuotingEventHandler_count{callName=\"handleQuoteResponseAcceptedEvt\"}[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FSPIOP - API Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method,route) (rate(http_request_duration_seconds_sum{app=\"fspiop-api-svc\",route!=\"/metrics\"}[$__interval]) / rate(http_request_duration_seconds_count{app=\"fspiop-api-svc\",route!=\"/metrics\"}[$__interval]) >= 0)",
     "legendFormat": "{{method}} {{route}}"
    },
    {
     "expr": "sum by (leg) (rate(http_request_duration_seconds_count{app=\"fspiop-api-svc\",route!=\"/metrics\"}[$__rate_interval])  >= 0)",
     "legendFormat": "Reqs / Sec"
    }
   ]
  },
  {
   "title": "FSPIOP - TransfersEventHandler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(QuotingEventHandler_sum[$__interval]) / rate(QuotingEventHandler_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Quoting Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Ops / sec (success)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(QuotingAggregate_count{success=\"true\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Ops / sec (error)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(AccountLookupAggregate_count{callName=\"handleAccountLookUpEvent\", success=\"false\"}[$__interval])  >= 0",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "handle QuoteRequest / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(QuotingAggregate_count{callName=\"_handleQuoteRequest\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "handle QuoteResponse / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(QuotingAggregate_count{callName=\"_handleQuoteResponse\"}[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Quoting Event Handler",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(QuotingEventHandler_Calls_sum[$__interval]) / rate(QuotingEventHandler_Calls_count[$__interval])  >= 0)",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg (QuotingEventHandler_batchSize)",
     "legendFormat": "Batch Size"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quoting Command Handler",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(QuotingAggregate_sum[$__interval]) / rate(QuotingAggregate_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (QuotingCommandHandler_batchSize )",
     "legendFormat": "Batch size"
    },
    {
     "expr": "avg by(callName) (rate(QuotingCommandHandler_Calls_sum[$__interval]) / rate(QuotingCommandHandler_Calls_count[$__interval])  >= 0)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}