{
 "title": "vNext Transfer",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusSource", "label": "PrometheusDataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Simulators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(Simulator_transfers_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Max total time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (max((rate(Simulator_transfers_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_transfers_count{leg=\"total\"}[$__rate_interval]))>=0) [$__range:$__rate_interval])",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Avg time (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ((rate(Simulator_transfers_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_transfers_count{leg=\"total\"}[$__rate_interval])>=0)\n)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Req(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(increase(Simulator_transfers_count{leg=\"total\"}[$__range])  >= 0)",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(TransfersAggregate_count{success=\"false\"}[$__range])) OR vector(0)",
     "legendFormat": "Cmd Handler"
    },
    {
     "expr": "sum(count_over_time(TransfersEventHandler_Calls_count{success=\"false\"}[$__interval]) OR vector(0))",
     "legendFormat": "Evt Handler"
    }
   ]
  },
  {
   "title": "Durations Measured at the Simulators",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (leg) ((rate(Simulator_transfers_sum[$__rate_interval]) / rate(Simulator_transfers_count[$__rate_interval])) >=0)\n\n",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (leg) (rate(Simulator_transfers_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "Transfers/Sec"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TransfersEventHandler batchSize (avg)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(TransfersEventHandler_batchSize)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PrepareTransferCmd /sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(TransfersAggregate_CommandsProcessed{commandName=\"PrepareTransferCmd\"}[$__rate_interval])",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  {
   "title": "Max total time (ms)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time (max((rate(Simulator_transfers_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_transfers_count{leg=\"total\"}[$__rate_interval]))>=0) [$__range:$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(Simulator_transfers_count{success=\"false\"})",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  {
   "title": "transfers /sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (leg) (rate(TransfersDuration_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  {
   "title": "TransfersCommadHandler batchSize (avg)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(TransfersCommandHandler_batchSize)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CommitTransferFulfilCmd /sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rate(TransfersAggregate_CommandsProcessed{commandName=\"CommitTransferFulfilCmd\"}[$__rate_interval]))",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  {
   "title": "Avg time (ms)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg ((rate(Simulator_transfers_sum{leg=\"total\"}[$__rate_interval]) / rate(Simulator_transfers_count{leg=\"total\"}[$__rate_interval])>=0)\n)",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  { "title": "FSPIOP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "FSPIOP - API Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(method,route) (rate(http_request_duration_seconds_sum{app=\"fspiop-api-svc\",route=~\"/transfers/.*\"}[$__interval]) / rate(http_request_duration_seconds_count{app=\"fspiop-api-svc\",route=~\"/transfers/.*\"}[$__interval]) >= 0)",
     "legendFormat": "{{method}} {{route}}"
    },
    {
     "expr": "sum by (leg) (rate(http_request_duration_seconds_count{app=\"fspiop-api-svc\",route!=\"/metrics\"}[$__rate_interval])  >= 0)",
     "legendFormat": "Reqs / Sec"
    }
   ]
  },
  {
   "title": "FSPIOP - TransfersEventHandler",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(TransferEventHandler_sum[$__interval]) / rate(TransferEventHandler_count[$__interval])  >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transfers Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "FSPIOP Handler Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum (kafka_consumergroup_lag_sum{consumergroup=\"interop-apis-bc_fspiop-event-handler-svc_TransferEventHandler\"} OR vector(0)) ) /\n( sum((irate(kafka_topic_partition_current_offset{topic=\"TransfersBcRequests\"}[$__interval])) /2) )",
     "legendFormat": "Load"
    },
    {
     "expr": "kafka_consumergroup_members{consumergroup=\"interop-apis-bc_fspiop-event-handler-svc_TransferEventHandler\"}",
     "legendFormat": "Instances"
    },
    {
     "expr": "abs(kafka_consumergroup_lag_sum{consumergroup=\"interop-apis-bc_fspiop-event-handler-svc_TransferEventHandler\"})",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Event Handler Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum (kafka_consumergroup_lag_sum{consumergroup=\"transfers-bc_event-handler-svc\"} OR vector(0)) ) /\n( sum((irate(kafka_topic_partition_current_offset{topic=\"TransfersBcRequests\"}[$__interval])) /2) )",
     "legendFormat": "Load"
    },
    {
     "expr": "kafka_consumergroup_members{consumergroup=\"transfers-bc_event-handler-svc\"}",
     "legendFormat": "Instances"
    },
    {
     "expr": "sum(abs (kafka_consumergroup_lag_sum{consumergroup=\"transfers-bc_event-handler-svc\"} )  OR vector(0))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Command Handler Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum (kafka_consumergroup_lag_sum{consumergroup=\"transfers-bc_command-handler-svc\"} OR vector(0)) ) /\n( sum((irate(kafka_topic_partition_current_offset{topic=\"TransfersBcRequests\"}[$__interval])) /2) )",
     "legendFormat": "Load"
    },
    {
     "expr": "kafka_consumergroup_members{consumergroup=\"transfers-bc_command-handler-svc\"}",
     "legendFormat": "Instances"
    },
    {
     "expr": "sum(abs(kafka_consumergroup_lag_sum{consumergroup=\"transfers-bc_command-handler-svc\"})  OR vector(0))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Durations Measured at the EventHandlers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(leg) (rate(TransfersDuration_sum[$__rate_interval]) / rate(TransfersDuration_count[$__rate_interval]))",
     "legendFormat": "{{leg}}"
    },
    {
     "expr": "sum by (leg) (rate(TransfersDuration_count{leg=\"total\"}[$__rate_interval])  >= 0)",
     "legendFormat": "Transfers/Sec"
    }
   ]
  },
  {
   "title": "Event Handlers Durations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(TransfersEventHandler_Calls_sum[$__rate_interval]) / rate(TransfersEventHandler_Calls_count[$__rate_interval]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(TransfersAggregate_participantsAdapter_sum[$__rate_interval]) / rate(TransfersAggregate_participantsAdapter_count[$__rate_interval]))",
     "legendFormat": "EvtHandler - {{callName}}"
    },
    {
     "expr": "avg (TransfersEventHandler_batchSize)",
     "legendFormat": "Avg BatchSize"
    }
   ]
  },
  {
   "title": "Command & Event Handlers Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(TransfersCommandHandler_Calls_sum[$__rate_interval]) / rate(TransfersCommandHandler_Calls_count[$__rate_interval]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(TransfersAggregate_sum[$__rate_interval]) / rate(TransfersAggregate_count[$__rate_interval]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(TransfersAggregate_participantsAdapter_sum[$__rate_interval]) / rate(TransfersAggregate_participantsAdapter_count[$__rate_interval]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg (TransfersCommandHandler_batchSize)",
     "legendFormat": "Avg BatchSize"
    }
   ]
  },
  {
   "title": "Command Handlers - A&B Client Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(AccountsAndBalancesClient_sum[$__rate_interval]) / rate(AccountsAndBalancesClient_count[$__rate_interval]))",
     "legendFormat": "A&BClient - {{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(BuiltinLedgerDataPlaneClient_sum[$__rate_interval]) / rate(BuiltinLedgerDataPlaneClient_count[$__rate_interval]))",
     "legendFormat": "A&BClient Builtin - {{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(TigerBeetleDataPlaneClient_sum[$__rate_interval]) / rate(TigerBeetleDataPlaneClient_count[$__rate_interval]))",
     "legendFormat": "A&BClient TB - {{callName}}"
    }
   ]
  },
  { "title": "Accounts and Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Accounts&Balances Builtin Ledger Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(BuiltinLedgerGrpcHandler_sum[30s]) / rate(BuiltinLedgerGrpcHandler_count[30s]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(BuiltinLedgerAggregate_sum[30s]) / rate(BuiltinLedgerAggregate_count[30s]))",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Accounts&Balances CoA Durations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(GrpcHandler_sum[30s]) / rate(GrpcHandler_count[30s]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(AccountsAndBalancesAggregate_sum[30s]) / rate(AccountsAndBalancesAggregate_count[30s]))",
     "legendFormat": "{{callName}}"
    }
   ]
  }
 ]
}