{
 "title": "vNext Transfer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TransfersEventHandler batchSize",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TransfersEventHandler_batchSize",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TransfersCommadHandler batchSize",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TransfersCommandHandler_batchSize",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PrepareTransferCmd /sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(TransfersAggregate_CommandsProcessed{commandName=\"PrepareTransferCmd\"}[$__rate_interval])",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  {
   "title": "CommitTransferFulfilCmd /sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(TransfersAggregate_CommandsProcessed{commandName=\"CommitTransferFulfilCmd\"}[30s])",
     "legendFormat": "{{commandName}}"
    }
   ]
  },
  { "title": "Transfers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(leg) (rate(TransfersDuration_sum[30s]) / rate(TransfersDuration_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Handler Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(TransfersCommandHandler_Calls_sum[30s]) / rate(TransfersCommandHandler_Calls_count[30s]))",
     "legendFormat": "CmdHandler - {{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(TransfersAggregate_sum[30s]) / rate(TransfersAggregate_count[30s]))",
     "legendFormat": "CmdAgg - {{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(TransfersEventHandler_Calls_sum[30s]) / rate(TransfersEventHandler_Calls_count[30s]))",
     "legendFormat": "EvtHandler - {{callName}}"
    }
   ]
  },
  { "title": "Accounts and Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Accounts&Balances CoA Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(GrpcHandler_sum[30s]) / rate(GrpcHandler_count[30s]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(AccountsAndBalancesAggregate_sum[30s]) / rate(AccountsAndBalancesAggregate_count[30s]))",
     "legendFormat": "{{callName}}"
    }
   ]
  },
  {
   "title": "Accounts&Balances Builtin Ledger Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(callName) (rate(BuiltinLedgerGrpcHandler_sum[30s]) / rate(BuiltinLedgerGrpcHandler_count[30s]))",
     "legendFormat": "{{callName}}"
    },
    {
     "expr": "avg by(callName) (rate(BuiltinLedgerAggregate_sum[30s]) / rate(BuiltinLedgerAggregate_count[30s]))",
     "legendFormat": "{{callName}}"
    }
   ]
  }
 ]
}