apiVersion: v2
description: Helm chart for mojaloop vNext infrastructure services
name: vnext-infra
version: 15.0.0
appVersion: "kafka: 3.5.1; console: 2.3.2; mongodb: 6.0.8; mongo-express: 0.54.0; elasticsearch:19.9.2; redis: 17.11.6"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
- https://github.com/mojaloop/mojaloop
- https://github.com/mojaloop/platform-shared-tools
maintainers:
- name: Tom Daly
  email: tomd@crosslaketech.com
dependencies:
## kafka 
- name: kafka
  alias: kafka
  condition: kafka.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - mojaloop
  - dependency
  - vNext
  - kafka
  version: 24.0.11
## redpanda kafka console 
- name: console
  alias: redpanda-console
  condition: console.enabled
  repository: https://charts.redpanda.com
  tags:
  - mojaloop
  - dependency
  - vNext
  - kafka
  - redpanda
  version: 0.7.2
## MongoDB
- name: mongodb
  alias: mongodb
  condition: mongodb.enabled
  repository: https://charts.bitnami.com/bitnami
  tags:
  - mojaloop
  - dependency
  - vNext
  - mongodb
  version: 13.3.1
## Mongo-express
- name: mongo-express
  alias: mongo-express
  condition: mongo-express.enabled
  repository: https://cowboysysop.github.io/charts/
  tags:
  - mojaloop
  - dependency
  - vNext
  - mongodb
  version: 3.1.1
## redis 
- name: redis
  alias: redis 
  condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
  tags:
  - mojaloop
  - dependency
  - vNext
  - mongodb
  version: 17.11.6
## Elastic Search Kibana 
- name: elasticsearch
  alias: elasticsearch
  condition: elasticsearch.enabled
  repository: https://charts.bitnami.com/bitnami
  tags:
  - mojaloop
  - dependency
  - vNext
  - elasticsearch
  version: 19.9.2
