kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: vnext-installs.vnext.mojaloop.io
spec:
  group: vnext.mojaloop.io
  scope: Namespaced
  names:
    plural: vnext-installs
    singular: vnext-install
    shortNames:
      - mli
    kind: MojaloopVNextInstall
    listKind: MojaloopVNextInstallList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: MojaloopVNextInstall is the Schema for MojaloopVNextInstall API
          type: object
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase.
                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: MojaloopVNextInstall.spec describes the desired state of my resource
              type: object
              required:
                - services
              properties:
                configOverride:
                  type: object
                  properties:
                    KAFKA_URL:
                      type: string
                    MONGO_URL:
                      type: string
                services:
                  description: >-
                    List of services to deploy
                  type: array
                  items:
                    description: The name of a pod created by the operator.
                    type: object
                    properties:
                      svcName:
                        type: string
                      image:
                        type: string
                      bcName:
                        type: string
                      layer:
                        type: string
                      size:
                        type: number
            status:
              description: The status of this MojaloopVNextInstall resource, set by the operator.
              type: object
              properties:
                pods:
                  description: The list of pods created by the operator.
                  type: array
                  items:
                    description: The name of a pod created by the operator.
                    type: string
                lastChangedBy:
                  description: test param.
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
  conversion:
    strategy: None
