apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mojaloop.service: settlements-reporting-svc
    mojaloop.layer: reporting
  name: settlements-reporting-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: settlements-reporting-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mojaloop.service: settlements-reporting-svc
        mojaloop.layer: reporting
    spec:
      containers:
        - env:
          - name: SETTLEMENTS_SVC_URL
            value: http://settlements-api-svc:3600
          envFrom:
            - configMapRef:
                name: vnext-configs
          image: mojaloop/reporting-bc-settlements-reporting-svc:0.3.18
          livenessProbe:
            exec:
              command:
                - nc -z localhost 5004 || exit -1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: settlements-reporting-svc
          ports:
            - containerPort: 5004
          resources: {}
      restartPolicy: Always
